name: Day13-ci

on: 
  push:
    branches: [main]

jobs:
  run_api:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-python@v5
        with:
          python-version: '3.11'

      - run: pip install -r DAY_13/requirements.txt pytest
      - run: cd DAY_13 && pytest